/* Generated By:JavaCC: Do not edit this line. PROMELAParserTreeConstants.java Version 5.0 */
package com.googlecode.promnetpp.parsing;

public interface PROMELAParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSPECIFICATION = 1;
  public int JJTUNIT = 2;
  public int JJTCOMMENT = 3;
  public int JJTDEFINEDIRECTIVE = 4;
  public int JJTTYPEDEFINITION = 5;
  public int JJTSIMPLEDECLARATION = 6;
  public int JJTMULTIDECLARATION = 7;
  public int JJTTYPENAME = 8;
  public int JJTGLOBALDECLARATION = 9;
  public int JJTCHANNELINITIALIZATION = 10;
  public int JJTFUNCTIONDEFINITION = 11;
  public int JJTFUNCTIONPARAMETERS = 12;
  public int JJTINSTRUCTIONLIST = 13;
  public int JJTINSTRUCTION = 14;
  public int JJTNONBLOCKINSTRUCTION = 15;
  public int JJTSENDSTATEMENT = 16;
  public int JJTRECEIVESTATEMENT = 17;
  public int JJTINCREMENT = 18;
  public int JJTDECREMENT = 19;
  public int JJTASSIGNMENT = 20;
  public int JJTBREAK = 21;
  public int JJTDOLOOP = 22;
  public int JJTFORLOOP = 23;
  public int JJTIF = 24;
  public int JJTELSE = 25;
  public int JJTRUN = 26;
  public int JJTSKIP = 27;
  public int JJTVARIABLE = 28;
  public int JJTEXPRESSION = 29;
  public int JJTTERM = 30;
  public int JJTFACTOR = 31;
  public int JJTFUNCTIONCALL = 32;
  public int JJTFUNCTIONCALLPARAMETERS = 33;
  public int JJTBLOCKINSTRUCTION = 34;
  public int JJTATOMICBLOCK = 35;
  public int JJTDSTEPBLOCK = 36;
  public int JJTPROCESSDEFINITION = 37;
  public int JJTINITPROCESSDEFINITION = 38;


  public String[] jjtNodeName = {
    "Start",
    "Specification",
    "Unit",
    "Comment",
    "DefineDirective",
    "TypeDefinition",
    "SimpleDeclaration",
    "MultiDeclaration",
    "TypeName",
    "GlobalDeclaration",
    "ChannelInitialization",
    "FunctionDefinition",
    "FunctionParameters",
    "InstructionList",
    "Instruction",
    "NonBlockInstruction",
    "SendStatement",
    "ReceiveStatement",
    "Increment",
    "Decrement",
    "Assignment",
    "Break",
    "DoLoop",
    "ForLoop",
    "If",
    "Else",
    "Run",
    "Skip",
    "Variable",
    "Expression",
    "Term",
    "Factor",
    "FunctionCall",
    "FunctionCallParameters",
    "BlockInstruction",
    "AtomicBlock",
    "DStepBlock",
    "ProcessDefinition",
    "InitProcessDefinition",
  };
}
/* JavaCC - OriginalChecksum=0321aef0265695b6f541302ac47acd83 (do not edit this line) */
